### ISSUE TITLE
FA - PT 3000000

### ISSUE THREAD

**Issue by ViniciusBVilar** [TesteProGest/progest#25]

**Comment by xanderayes** [comment]
![Text](foo.png)

**Comment by xanderayes** [comment]
<html>
                <head>
                    <title>Total_time= 0:0:14</title>
                </head>
                <body>
                    <figure>
                        <img src= "http://i.imgur.com/tvjg8LD.png" alt="graphs" />
                    </figure>

```
            </body>
        </html>
```
